models:
  Claude 3.7 Sonnet:
    model_id: "us.anthropic.claude-3-7-sonnet-20250219-v1:0" 
    input_format: "multimodal"
    temperature: 1.0
    top_p: 1.0
    top_k: 500
    max_tokens: 8192
    memory_window: 10
    max_top_k: 500
  Claude 3.5 Haiku:
    model_id: "anthropic.claude-3-5-haiku-20241022-v1:0"
    input_format: "multimodal"
    temperature: 1.0
    top_p: 1.0
    top_k: 500
    max_tokens: 4096
    memory_window: 10
    max_top_k: 500
  Amazon Nova Pro:
    model_id: "us.amazon.nova-pro-v1:0"
    input_format: "multimodal"
    temperature: 1.0
    top_p: 1.0
    top_k: 128
    max_tokens: 5000
    memory_window: 10
    max_top_k: 128
  Amazon Nova Lite:
    model_id: "us.amazon.nova-lite-v1:0"
    input_format: "multimodal"
    temperature: 1.0
    top_p: 1.0
    top_k: 128
    max_tokens: 5000
    memory_window: 10
    max_top_k: 128
  Amazon Nova Micro:
    model_id: "us.amazon.nova-micro-v1:0"
    input_format: "text"
    temperature: 1.0
    top_p: 1.0
    top_k: 128
    max_tokens: 5000
    memory_window: 10
    max_top_k: 128
  Mistral Large 2:
    model_id: "mistral.mistral-large-2407-v1:0"
    input_format: "text"
    temperature: 1.0
    top_p: 1.0
    top_k: 200
    max_tokens: 4096
    memory_window: 10
    max_top_k: 200
